/* This file was generated by SableCC (http://www.sablecc.org/). */

package tessauro.analysis;

import tessauro.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTTipoPrimitivo(TTipoPrimitivo node);
    void caseTIdent(TIdent node);
    void caseTNumDec(TNumDec node);
    void caseTNumBin(TNumBin node);
    void caseTAtrib(TAtrib node);
    void caseTPv(TPv node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTBlank(TBlank node);
    void caseTComentario(TComentario node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
