/* This file was generated by SableCC (http://www.sablecc.org/). */

package tessauro.node;

import tessauro.analysis.*;

@SuppressWarnings("nls")
public final class TAtribConst extends Token
{
    public TAtribConst()
    {
        super.setText("=");
    }

    public TAtribConst(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtribConst(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtribConst(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtribConst text.");
    }
}
