/* This file was generated by SableCC (http://www.sablecc.org/). */

package tessauro.node;

import tessauro.analysis.*;

@SuppressWarnings("nls")
public final class TV extends Token
{
    public TV()
    {
        super.setText(",");
    }

    public TV(int line, int pos)
    {
        super.setText(",");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TV(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTV(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TV text.");
    }
}
