/* This file was generated by SableCC (http://www.sablecc.org/). */

package tessauro.node;

import tessauro.analysis.*;

@SuppressWarnings("nls")
public final class TValChar extends Token
{
    public TValChar(String text)
    {
        setText(text);
    }

    public TValChar(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TValChar(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTValChar(this);
    }
}
